#一键发到底
#1.先build
#2.再停容器、删容器
#3.用刚构建好的镜像启容器

variables:
  container_name: "canyon-v2"
  docker_port: 15457

stages:
  - build
  - pre
  - deploy

build:
  stage: build
  script:
    - echo ${container_name}:$CI_COMMIT_SHA
    - docker build -t ${container_name}:$CI_COMMIT_SHA .
    - docker images

pre:
  stage: pre
  script:
    - ls
    - docker stop ${container_name}
    - docker rm ${container_name}
  allow_failure: true

deploy:
  stage: deploy
  script:
    - docker run  -p ${docker_port}:8080 -d --name ${container_name} ${container_name}:$CI_COMMIT_SHA
